AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using GadgetHub.Domain.Abstract;
using GadgetHub.Domain.Entities;
using System.Linq;
using System.Web;

namespace GadgetHub.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IGadgetRepository repository;

        public AdminController(IGadgetRepository repo)
        { 
            repository = repo;
        }

        public ActionResult Index()
        {
            return View(repository.Gadgets);
        }

        public ViewResult Edit(int gadgetID)
        { 
            Gadget gadget = repository.Gadgets.FirstOrDefault(g => g.GadgetID == gadgetID);
            return View(gadget);
        }

        [HttpPost]
        public ActionResult Edit(Gadget gadget, HttpPostedFileBase image=null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    gadget.ImageMimeType = image.ContentType;
                    gadget.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(gadget.ImageData, 0,
                    image.ContentLength);
                }
                repository.SaveGadget(gadget);
                TempData["message"] = string.Format("{0} has been saved.", gadget.GadgetName);
                return RedirectToAction("Index");
            }

            else
            {
                return View(gadget);
            }
        }

        public ViewResult Create()
        {
            ViewBag.operation = "create";
            return View("Edit", new Gadget());
        }

        [HttpPost]
        public ActionResult Delete(int gadgetID)
        {
            Gadget deletedGadget = repository.DeleteGadget(gadgetID);
            if (deletedGadget != null)
            {
                TempData["message"] = string.Format("{0} was deleted.", deletedGadget.GadgetName);
            }
            return RedirectToAction("Index");
        }
    }
}

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Controllers/GadgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GadgetHub.Domain.Abstract;
using GadgetHub.Domain.Entities;
using GadgetHub.WebUI.Models;

namespace GadgetHub.WebUI.Controllers
{
    public class GadgetController : Controller
    {
        private IGadgetRepository gadgetRepository;

        public GadgetController(IGadgetRepository gadgetRepository)
        {
            this.gadgetRepository = gadgetRepository;
        }

        public int PageSize = 4;

        public ViewResult List(string category, int page = 1)
        {
            GadgetsListViewModel model = new GadgetsListViewModel
            {
                Gadgets = gadgetRepository.Gadgets.Where(g => category == null || g.GadgetCategory == category).OrderBy(g => g.GadgetID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,

                    //TotalItems = gadgetRepository.Gadgets.Count()

                    TotalItems = category == null ? gadgetRepository.Gadgets.Count() : gadgetRepository.Gadgets.Where(e => e.GadgetCategory == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int gadgetId)
        {
            Gadget _gadget = gadgetRepository.Gadgets.FirstOrDefault(g => g.GadgetID == gadgetId);

            if (_gadget != null)
            {
                return File(_gadget.ImageData, _gadget.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Views/Admin/Edit.cshtml
@model GadgetHub.Domain.Entities.Gadget

@{
    var operationText = "";
    if (ViewBag.operation == "create")
    {
        operationText = "Add new Gadget";
    }
    else
    {
        operationText = "Edit " + Model.GadgetName;
    }

    ViewBag.Title = "Admin:" + operationText;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>@operationText</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="card-body">
            @Html.HiddenFor(m => m.GadgetID)

            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "GadgetID":
                    case "ImageData":
                    case "ImageMimeType":
                        break;
                    default:
                        <div class="mb-3">
                            <label class="form-label">
                                @(property.DisplayName ?? property.PropertyName)
                            </label>

                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }

            <div class="mb-3">
                <label class="form-label">Image</label>
                <div style="position:relative;">
                    <a class="btn btn-secondary" href="javascript:;">
                        Choose File
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                               left:0;opacity:0;
                               background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());' />
                    </a>
                    <span class="form-label label-info" id="upload-file-info"></span>
                </div>

                @if (Model.ImageData == null)
                {
                    <div class="form-text">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src='@Url.Action("GetImage", "Gadget", new { @Model.GadgetID })' />
                }
            </div>
        </div>

        <div class="card-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to list", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    }
</div>

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<GadgetHub.Domain.Entities.Gadget>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="card">
    <div class="card-header">
        <h3>All Products</h3>
    </div>

	<div class="card-body">
		<table class="table table-striped table-condensed table-bordered">
			<tr>
				<th class="text-right">
					ID
				</th>
				<th>
					Name
				</th>
				<th class="text-right">
					Price
				</th>
				<th class="text-center">
					Actions
				</th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td>
						@item.GadgetID
					</td>
					<td>
						@Html.ActionLink(item.GadgetName, "Edit", new { item.GadgetID })
					</td>
					<td>
						@item.GadgetPrice.ToString("c")
					</td>
					<td class="text-center">
						@using (Html.BeginForm("Delete", "Admin"))
						{
							@Html.Hidden("GadgetID", item.GadgetID)
							<input type="submit" class="btn btn-primary" value="Delete" />
						}
					</td>
				</tr>
			}

		</table>
	</div>

	<div class="card-footer">
		@Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-primary" })
	</div>
</div>