AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using GadgetHub.Domain.Abstract;
using GadgetHub.Domain.Entities;
using GadgetHub.WebUI.Models;

namespace GadgetHub.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGadgetRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGadgetRepository repo, IOrderProcessor proc)
        { 
            repository = repo;
            orderProcessor = proc;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int gadgetID, string returnUrl)
        { 
            Gadget gadget = repository.Gadgets.FirstOrDefault(g => g.GadgetID == gadgetID);

            if (gadget != null)
            {
                cart.AddItem(gadget, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

		public RedirectToRouteResult RemoveFromCart(Cart cart, int gadgetID, string returnUrl)
		{
			Gadget gadget = repository.Gadgets.FirstOrDefault(g => g.GadgetID == gadgetID);

			if (gadget != null)
			{
				cart.RemoveLine(gadget);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is currently empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.ClearCart();
                return View("Completed", shippingDetails);
            }

            else
            {
                return View(shippingDetails);
            }
        }
    }
}

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Controllers/GadgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GadgetHub.Domain.Abstract;
using GadgetHub.Domain.Entities;
using GadgetHub.WebUI.Models;

namespace GadgetHub.WebUI.Controllers
{
    public class GadgetController : Controller
    {
        private IGadgetRepository gadgetRepository;

        public GadgetController(IGadgetRepository gadgetRepository)
        {
            this.gadgetRepository = gadgetRepository;
        }

        public int PageSize = 4;

        public ViewResult List(string category, int page = 1)
        {
            GadgetsListViewModel model = new GadgetsListViewModel
            {
                Gadgets = gadgetRepository.Gadgets.Where(g => category == null || g.GadgetCategory == category).OrderBy(g => g.GadgetID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,

                    //TotalItems = gadgetRepository.Gadgets.Count()

                    TotalItems = category == null ? gadgetRepository.Gadgets.Count() : gadgetRepository.Gadgets.Where(e => e.GadgetCategory == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int gadgetId)
        {
            Gadget _gadget = gadgetRepository.Gadgets.FirstOrDefault(g => g.GadgetID == gadgetId);

            if (_gadget != null)
            {
                return File(_gadget.ImageData, _gadget.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GadgetHub.Domain.Abstract;

namespace GadgetHub.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGadgetRepository repository;

        public NavController(IGadgetRepository repo)
        { 
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Gadgets.Select(x => x.GadgetCategory).Distinct().OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Views/Shared/GadgetSummary.cshtml
@model GadgetHub.Domain.Entities.Gadget

<div class="card p-3 bg-light text-dark mb-2">

	@if (Model.ImageData != null)
	{
		<div class="pull-left" style="margin-right: 10px">
			<img class="img-thumbnail" width="75" height="75"
				 src="@Url.Action("GetImage", "Gadget", new { Model.GadgetID })" />
		</div>
	}

	<h3>
		<strong>@Model.GadgetName</strong>
		<span class="badge bg-primary float-end">
			@Model.GadgetPrice.ToString("c")
		</span>
	</h3>

	<span class="lead">@Model.GadgetDesc</span>

	@using (Html.BeginForm("AddToCart", "Cart"))
	{ 
		<div class="float-end">
			@Html.HiddenFor(x => x.GadgetID)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)

			<input type="submit" class="btn btn-success" value="Add to cart" />
		</div>
	}

</div>

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/ErrorStyles.css" rel="stylesheet" />

	<script src="~/Scripts/jquery-1.4.1.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

	<title>@ViewBag.Title</title>
</head>
<body>
    <div>
		@if (TempData["message"] != null)
		{
			<div class="alert alert-success">
				@TempData["message"]
			</div>
		}
        @RenderBody()
    </div>
</body>
</html>

AD2 Homework 1/GadgetHub/GadgetHub.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @*Link bootstrap style sheet*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <title>@ViewBag.Title </title>
</head>
<body>

    <div class="navbar navbar-dark bg-dark">
        <a class="navbar-brand ms-4" href="#">GADGET HUB</a>
		@Html.Action("Summary", "Cart")
    </div>

	<div class="row border p-3">
		<div id="categories" class="col-3">
			@Html.Action("Menu", "Nav")
		</div>

		<div class="col-9">
			@RenderBody()
		</div>
	</div>
</body>
</html>